development:
  adapter: postgresql
  encoding: utf8
  database: ogb_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: ogb_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: ogb_production
  pool: 5
  username: 
  password:
